// <auto-generated />
using System;
using HostTool.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HostTool.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250920060032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("HostTool.Domain.Scheduler", b =>
                {
                    b.Property<Guid>("SchedulerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RunAll")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchedulerDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchedulerId");

                    b.ToTable("Schedulers");
                });

            modelBuilder.Entity("HostTool.Domain.SchedulerDay", b =>
                {
                    b.Property<Guid>("SchedulerDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SchedulerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SchedulerDayId");

                    b.ToTable("SchedulerDays");
                });
#pragma warning restore 612, 618
        }
    }
}
